# Generated by Django 2.2.5 on 2020-05-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wastage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('registration_D', models.DateField()),
                ('expiry_D', models.DateField()),
                ('price', models.FloatField()),
                ('quantity', models.PositiveIntegerField()),
                ('donor', models.CharField(max_length=100)),
            ],
        ),
    ]
