# Generated by Django 2.2.5 on 2020-04-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='provider',
            fields=[
                ('donor_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('donor_status', models.BooleanField(default=False)),
                ('anonymous_s', models.BooleanField(default=False)),
            ],
        ),
    ]
