# Generated by Django 2.2.5 on 2020-04-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='anonymous_s',
            new_name='anonymous_status',
        ),
    ]
