# Generated by Django 3.0.3 on 2020-04-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20200426_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='donor_status',
            field=models.CharField(max_length=50),
        ),
    ]
