# Generated by Django 3.0.3 on 2020-04-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_auto_20200428_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='anonymous_status',
            field=models.CharField(max_length=3),
        ),
    ]
