# Generated by Django 2.2.5 on 2020-05-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_auto_20200503_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='id',
        ),
        migrations.AlterField(
            model_name='provider',
            name='donor_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
