# Generated by Django 2.2.5 on 2020-05-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_auto_20200503_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='user_name',
            field=models.CharField(default='User', max_length=50),
        ),
    ]
