# Generated by Django 2.2.5 on 2020-05-08 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0007_provider_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='anonymous_status',
        ),
    ]
