# Generated by Django 3.0.3 on 2020-05-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0008_remove_provider_anonymous_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='anonymus_status',
            field=models.BooleanField(default=False),
        ),
    ]
