# Generated by Django 2.2.5 on 2020-04-29 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='item_name',
        ),
    ]
