# Generated by Django 2.2.5 on 2020-05-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20200504_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='item_name',
            field=models.CharField(default='Wait', max_length=100),
        ),
        migrations.AddField(
            model_name='checkout',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
