# Generated by Django 2.2.5 on 2020-05-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20200505_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='donor',
            field=models.CharField(default='wait', max_length=50),
        ),
    ]
