# Generated by Django 2.2.5 on 2020-05-06 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_checkout_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='item_in_inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory'),
        ),
    ]
