# Generated by Django 3.0.3 on 2020-05-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20200506_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='item_in_inventory',
            field=models.CharField(default='Item', max_length=100),
        ),
    ]
