# Generated by Django 2.2.5 on 2020-04-26 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
