# Generated by Django 2.2.5 on 2020-04-29 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_auto_20200428_0140'),
        ('inventory', '0004_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='donor',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='donor', to='provider.provider'),
            preserve_default=False,
        ),
    ]
