# Generated by Django 2.2.5 on 2020-05-03 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_donor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='donor',
        ),
    ]
