# Generated by Django 3.0.3 on 2020-05-14 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0009_provider_anonymus_status'),
        ('inventory', '0007_inventory_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donor', to='provider.provider'),
        ),
    ]
